config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :company do
    member do
      get :chat_testing
    end
    resources :invites
    resources :data
    resources :chat do
      get :chat
      post :create
    end
    resources :products do
      get :new
      post :create
      post :create_completions
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "presentation#index"
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :users
    has_many :invites
    has_many :products
    has_many :chats
    has_many :product_uploads
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  before_action :authenticate_user!

  def show
    @company = Company.find(current_user.company_id)
    @products = @company.products.take(10)
    @chat = Chat.create(company_id: @company.id)
  end

  def chat_testing
    @chat = Chat.create(company_id: current_user.company_id)
    @company = Company.find(current_user.company_id)
    # create chat message on @chat
    # create chat message on @chat
  end

end

app/helpers/company_helper.rb
module CompanyHelper
end

app/views/company/chat_testing.html.erb
<div class="mt-8">
<%= render partial: "chat/chat_window", locals: {company_id: @company.id, chat_id: @chat.id}%>
</div>

app/views/company/show.html.erb
<div class="min-h-screen flex gap-2">

  <%= render "layouts/sidebar", company_id: @company.id %>
  <div>
    <h1>
      <%= @company.name %>
      <%= @company.org_no %>
    </h1>
  <div class="h-80 overflow-y-scroll">
    <table class="border-collapse border border-slate-500">
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Brand</th>
        <th>Description</th>
      </tr>
      <tbody>
      <% @products.each do |product| %>
        <tr>
          <td class="border border-sky-800"><%= product.name %></td>
          <td class="border border-sky-800"><%= product.price %></td>
          <td class="border border-sky-800"><%= product.brand %></td>
          <td class="border border-sky-800"><%= product.description %></td>
        </tr>
      <% end %>
      </tbody>

    </table>
  </div>
    <%= link_to "Create product", new_company_product_url(@company.id) %>

    <%= render partial: "chat/chat_window", locals: {company_id: @company.id, chat_id: @chat.id}%>
  </div>
</div>