config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :company do
    member do
      get :chat_testing
    end
    resources :invites
    resources :data
    resources :chat do
      get :chat
      post :create
    end
    resources :products do
      get :new
      post :create
      post :create_completions
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "presentation#index"
end

app/views/layouts/_sidebar.html.erb
<div class="bg-blue-600 w-64 p-6">
        <div class="text-white mb-4">
            <h1 class="text-2xl font-bold">🏠 Home</h1>
        </div>
        <ul>
            <li class="text-white mb-2 hover:bg-blue-700 px-2 py-1 rounded">
                <%= link_to "📂 Data", company_data_url(company_id) %>
            </li>
            <li class="text-white mb-2 hover:bg-blue-700 px-2 py-1 rounded">
                💬 Chats
            </li>
            <li class="text-white mb-2 hover:bg-blue-700 px-2 py-1 rounded">
                ⚙️ API
            </li>
            <!-- Add more list items as needed -->
        </ul>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductAssistant</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= turbo_include_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>